/**
 * Created by 橘 on 2017/5/2.
 */
(function(){
    'use strict';
    var jingyujie=angular.module("jingyujie");
    jingyujie.service("artService",[function(){
        this.getArtList=function(callback){
            var data=[
                {
                    id:1,
                    name:"春色之美",
                    author:"金成哲",
                    date:"2017-04-05",
                    price:"20000",
                    pic:"../image/default.jpg",
                    desc:"材料：布面油画,尺寸：40X50cm,年代：2015年,签名：金成哲（韩文）,品相：完好",
                    details:[]
                },
                {
                    id:2,
                    name:"春色之美",
                    author:"金成哲",
                    date:"2017-04-05",
                    price:"20000",
                    pic:"../image/default.jpg",
                    desc:"材料：布面油画,尺寸：40X50cm,年代：2015年,签名：金成哲（韩文）,品相：完好",
                    details:[]
                },
                {
                    id:3,
                    name:"春色之美",
                    author:"金成哲",
                    date:"2017-04-05",
                    price:"20000",
                    pic:"../image/default.jpg",
                    desc:"材料：布面油画,尺寸：40X50cm,年代：2015年,签名：金成哲（韩文）,品相：完好",
                    details:[]
                },
                {
                    id:4,
                    name:"春色之美",
                    author:"金成哲",
                    date:"2017-04-05",
                    price:"20000",
                    pic:"../image/default.jpg",
                    desc:"材料：布面油画,尺寸：40X50cm,年代：2015年,签名：金成哲（韩文）,品相：完好",
                    details:[]
                },
                {
                    id:5,
                    name:"春色之美",
                    author:"金成哲",
                    date:"2017-04-05",
                    price:"20000",
                    pic:"../image/default.jpg",
                    desc:"材料：布面油画,尺寸：40X50cm,年代：2015年,签名：金成哲（韩文）,品相：完好",
                    details:[]
                },
                {
                    id:6,
                    name:"春色之美",
                    author:"金成哲",
                    date:"2017-04-05",
                    price:"20000",
                    pic:"../image/default.jpg",
                    desc:"材料：布面油画,尺寸：40X50cm,年代：2015年,签名：金成哲（韩文）,品相：完好",
                    details:[]
                },
                {
                    id:7,
                    name:"春色之美",
                    author:"金成哲",
                    date:"2017-04-05",
                    price:"20000",
                    pic:"../image/default.jpg",
                    desc:"材料：布面油画,尺寸：40X50cm,年代：2015年,签名：金成哲（韩文）,品相：完好",
                    details:[]
                },
                {
                    id:8,
                    name:"春色之美",
                    author:"金成哲",
                    date:"2017-04-05",
                    price:"20000",
                    pic:"../image/default.jpg",
                    desc:"材料：布面油画,尺寸：40X50cm,年代：2015年,签名：金成哲（韩文）,品相：完好",
                    details:[]
                }
            ];
            if(callback){
                callback(data);
            }
        }
    }]);
})();